---
kind: pipeline
name: validate quantum
trigger:
  event:
    - push

steps:
  - name: Validate configuration
    image: r.planetary-quantum.com/quantum-public/cli:2
    environment:
      QUANTUM_USER: drone-io-housekeeping-deployer
      QUANTUM_PASSWORD:
        from_secret: PORTAINER_PASSWORD
    commands:
      - quantum-cli validate

---
kind: pipeline
name: deploy-housekeeping
depends_on:
  - validate quantum
trigger:
  event:
    - tag

steps:
  - name: "Deploy: portainer-01"
    depends_on:
      - clone
    image: r.planetary-quantum.com/quantum-public/cli:2
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      QUANTUM_USER: drone-io-housekeeping-deployer
      QUANTUM_PASSWORD:
        from_secret: PORTAINER_PASSWORD
    commands:
      - >
        quantum-cli stack update --create
        --environment swarm
        --endpoint portainer-01 --stack system-prune
  - name: "Deploy: portainer-02"
    depends_on:
      - clone
    image: r.planetary-quantum.com/quantum-public/cli:2
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      QUANTUM_USER: drone-io-housekeeping-deployer
      QUANTUM_PASSWORD:
        from_secret: PORTAINER_PASSWORD
    commands:
      - >
        quantum-cli stack update --create
        --environment docker
        --endpoint portainer-02 --stack portainer-02-system-prune

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
