---
kind: pipeline
name: default

steps:
  - name: Deploy
    image: registry.internal.planetary-networks.de/quantum-public/cli:1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PORTAINER_USER: drone-io-housekeeping-deployer
      PORTAINER_PASSWORD:
        from_secret: PORTAINER_PASSWORD
    commands:
      - >
        quantum-cli stack update --create
        --endpoint portainer-01 --stack system-prune
    when:
      event: tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
